image: registry.gitlab.bsc.es/inb/elixir/software-observatory/biconda-importer:latest
stages:
  - prepare
  - test
  - main_task  

update_repo:
  stage: prepare
  script:
    # Check if the directory exists and is a git repo
    - | 
      if [ -d "bioconda-recipes/.git" ]; then
        echo "Repository directory exists. Pulling latest changes...";
        cd bioconda-recipes && git pull && cd ..
      else
        echo "Repository directory does not exist. Cloning...";
        # Clone the repo if it does not exist
        git clone https://github.com/bioconda/bioconda-recipes;
      fi

tests: 
  stage: test
  script: 
    - conda run -n bioconda-dev python -c "import sys; print(sys.version)"
    - conda run --no-capture-output -n bioconda-dev python3 -m unittest discover -v "$CI_PROJECT_DIR/test/"
  artifacts:
    when: always
    reports:
      junit: report.xml

run_metadata_import:
  stage: main_task
  script:
    - echo "⚙️ Running main task"
    - conda run -n bioconda-dev python -c "import sys; print(sys.version)"
    - conda run --no-capture-output -n bioconda-dev python3 main.py -l=DEBUG
    - |
      echo -e "\n\
      ✨ Execution finished"
  artifacts:
    expire_in: 4 weeks
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  timeout: 4h
